// var x="Nasrin";
// document.write(x+"<br>");
// x="Jahan";
// document.write(x);
// x="123.50";
// console.log(typeof(x));
// x=parseFloat(x);
// console.log(typeof(x));
// var first_name = "Nasrin";
// var last_name = "Jahan";
// var contact = '01835493825';
// var cn="Contact                                      :                                            ";
// document.write("First_Name :    "+first_name+"<br>");
// document.write("Last_Name  :    "+last_name+"<br>");
// document.write(cn+contact+"<br>");
// var x = document.getElementById("hedding1");
// var inpt = prompt("enter a value");
// x.innerHTML= inpt;
//  document.getElementsByClassName("hedding2")[0].innerHTML= "hedding2";
document.querySelector("li a").innerHTML = "hedding";
document.querySelector(".mydiv a").innerHTML = "hedding";